# Generated by Django 4.2.24 on 2026-06-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='planted', max_length=15)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.resource')),
            ],
        ),
    ]
